### ISSUE TITLE
'Something went wrong when processing your file"

### ISSUE THREAD

**Issue by maphew** [hueyy/docdocgoose#10]
I get this error but there's no indication of what exactly when wrong or what troubleshooting avenues there might be. Any suggestions?

![image](https://github.com/lacuna-technologies/docdocgoose/assets/486200/65039334-35fa-4414-962b-a663aeab6613)

I tried with both Chrome and Firefox on Windows 10.

**Comment by hueyy** [comment]
If you pop open the JS console via inspect element, a more detailed error
should be displayed. If you're comfortable sharing the file, I can also
look into this.

**Comment by maphew** [comment]
Thanks for the tip!

On intial page load I get:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/v2cb3a2ab87c5498db5ce7e6608cf55231689030342039. (Reason: CORS request did not succeed). Status code: (null).   
> 
> None of the “sha512” hashes in the integrity attribute match the content of the subresource. The computed hash is “z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==”. [view](https://docdocgoose.huey.xyz/pdf/view)  
> Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [web-client-content-script.js:1:407301](moz-extension://e014c181-f827-41af-bf4e-7842b3cb1a5b/web-client-content-script.js)
> Uncaught (in promise) TypeError: t is undefined  
>     NextJS 30  
> [view-1b99a11ede18d1a6.js:1:4838](https://docdocgoose.huey.xyz/_next/static/chunks/pages/pdf/view-1b99a11ede18d1a6.js)  
> Loading failed for the <script> with source “https://gc.zgo.at/count.js”.

There are no further console messages after dropping the problem pdf into the page. 

On another pdf, which is a single page scan of signed document, the doc is processed correctly and there are no errors in the rendered page. Console has a warning of _"Warning: decodeScan - unexpected MCU data, current marker is: ffff 2 pdf.worker.df7560ea.js:1:17818"_

Unfortunately I can't share the problem pdf. From my perspective this is no longer an issue as the situation which prompted me try Docdocgoose has moved on. However I'm happy to keep the file around a couple of days and share info from other troubleshooting steps if that would be helpful to the project.

**Comment by hueyy** [comment]
Hmm it does sound like an error thrown by [pdfcpu](https://github.com/pdfcpu/pdfcpu), which DocDocGoose uses in WASM form. My guess is that there's some security feature on the docs that is impeding the decoding. This can be quite tricky to troubleshoot without the actual doc. 

Glad that it's no longer an issue for you. If you do come across this issue in respect of any docs you can share, do let me know. Also, feel free to let me know if you encounter any other issues.

Thanks for raising this.

**Comment by maphew** [comment]
Closing as it's not an active problem for me anymore. I'll reopen if it happens again and I can share a reproducible recipe or pdf.
